### ISSUE TITLE
GPS Telemetry data and logging?

### ISSUE THREAD

**Issue by Redferne** [SpektrumFPV/SpektrumDocumentation#2]
Having issues with sending GPS Telemetry data. Not sure how to interpret the data structs.
I'm sending through a SR6100AT receiver to a DX5 Rugged. Looking at the screenshot below.
Speed, Altitude, Time & Sat count seems to be OK. But what is Distance, how is it calculated?
Also Heading/Course shows the wrong value. I'm sending 1638 as heading/course in both STRU_TELE_GPS_BINARY and STRU_TELE_GPS_LOC messages. I'm also missing display of Latitude, Longitude, HDOP, GPS Flags, and millisecond on the time display.

Also is it possible to log the telemetry data on the DX5 Rugged transmitter? Through the data port?

![image](https://user-images.githubusercontent.com/2379821/84015629-6e500c00-a97c-11ea-9464-372a3378ebed.png)

**Comment by SpektrumRC** [comment]
From Andy "Distance is calculated by the transmitter from the position of the GPS when it gets about 6 or 7 satellites.  We do not support GPS_BINARY yet.  He needs to use the old (BCD) pair (LOC/STAT).  Is he using BCD for Lat/Lon?  He needs to.  No way to log data from a 5C/Rugged.  He needs a 5Pro for that, or an air transmitter."

**Comment by SpektrumRC** [comment]
He also mentioned there is discussion about this topic on this rcgroups thread https://www.rcgroups.com/forums/showthread.php?1726960-Spektrum-Telemetry-reverse-engineered-make-DIY-sensors-%21

**Comment by Redferne** [comment]
Oh. Cool. I'll continue asking in the forum thread. Thanks!
